### ISSUE TITLE
XDG_DATA_DIRS not set 

### ISSUE THREAD

**Issue by theottm** [dalanicolai/mediator#1]
Hi ! Nice package, thanks for sharing :)

The first defvar statement failed by me because `XDG_DATA_DIRS` wasn't defined in my env.
I just set it manually
```
(defvar mediator-data-directories '("/usr/share/"
                                    "/usr/local/share/"))
```
before loading `mediator.el`

**Comment by dalanicolai** [comment]
Thanks for the feedback! I will add a comment in the README. I think this way of setting the variable will not work after I have implemented the fix because, if I am right, a `defvar` does not overwrite an earlier `defvar`. So you should use `setq` (or alternatively I guess you could also add the environment variable with `setenv`)

**Comment by theottm** [comment]
You're welcome ! Yes you're right, `defvar` only works the first time. That's why I set it before loading. But you are right it is probably cleaner to use `setq`
