### ISSUE TITLE
File expansion after completing-read using selectrum

### ISSUE THREAD

**Issue by theottm** [dalanicolai/mediator#3]
Nice new feature that you can now choose a file to open !

I got some error due to the way `call-process` expands the `file-name`.
For example when I want to open `~/Images/agenda.png` with `Eye of Mate` from a buffer with default directory `default-dir` i get
```
No images found in 'file://defafult-dir/~/Images/agenda.png'.
```
So apparently `call-process` is adding the default dir before the file name. Or at least it runs the command from there according to the documentation :
```The process runs in default-directory if that is local (as
determined by unhandled-file-name-directory), or "~" otherwise.```

Just adding `expand-file-name` in the command args solves it. Not sure if it is best practice through. Maybe setting temporarily `default-directory` to `nil` would be cleaner ? Not sure. I made a PR for my solution, you can decide.

**Comment by dalanicolai** [comment]
I guess using the expanded file name is fine indeed. But I want it to get expanded in even more places in the function, so I will not merge your PR but implement it in a slightly different way. But thanks again for your contribution!

FYI just a small comment. It is not really a new feature because this was already possible with an Ivy/helm/selectrum+embark action. But this is just a way to make the mediator function work directly with Embark (Embark somehow requires to get the file-path from the minibuffer, see [here](https://www.reddit.com/r/emacs/comments/ns55f0/mediator_a_very_simple_emacs_openwith_menu_for/h0l7vbc?utm_source=share&utm_medium=web2x&context=3)).

**Comment by theottm** [comment]
No problem, I think you have a better overview of how to implement it best.
Ah I see thanks for the explanation !
